version: "3.10"

services:
  db:
    env_file:
      - .env
    image: postgres:15.2
    environment:
      - POSTGRES_DB:${POSTGRES_DB_NAME}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
  
  web:
    env_file:
      - .env
    build: .
    expose: 
      - 8000
    environment:
      - POSTGRES_DB:${POSTGRES_DB_NAME}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_HOST:${POSTGRES_HOST}
      - POSTGRES_PORT:${POSTGRES_PORT}
    volumes:
      - static:/code/static/
      - media:/code/media/
      - test_media:/code/test_media/
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static:/code/static/
      - media:/code/media/
      - test_media:/code/test_media/
    depends_on:
      - web

volumes:
  static:
  media:
  test_media: